"""add social content to highlights

Revision ID: b9bfd7d0eb52
Revises: 52262baffc99
Create Date: 2026-03-14 18:31:02.286627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9bfd7d0eb52'
down_revision: Union[str, None] = '52262baffc99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlight_clips', sa.Column('social_caption', sa.Text(), nullable=True))
    op.add_column('highlight_clips', sa.Column('hashtags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('highlight_clips', 'hashtags')
    op.drop_column('highlight_clips', 'social_caption')
    # ### end Alembic commands ###
