from __future__ import annotations
import os
from typing import Optional
from app.infrastructure.ai.transcription.base import TranscriptChunkData


def _format_srt_time(seconds: float) -> str:
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int((seconds % 1) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def _format_vtt_time(seconds: float) -> str:
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int((seconds % 1) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d}.{ms:03d}"


def _format_ass_time(seconds: float) -> str:
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    cs = int((seconds % 1) * 100)
    return f"{h:1d}:{m:02d}:{s:02d}.{cs:02d}"


class SubtitleGenerator:
    def generate_srt(
        self,
        chunks: list[TranscriptChunkData],
        sermon_start: float,
        output_path: str,
        sermon_end: Optional[float] = None,
    ) -> str:
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        lines: list[str] = []
        
        filtered_chunks = [
            c for c in chunks 
            if c.start_seconds >= sermon_start 
            and (sermon_end is None or c.end_seconds <= sermon_end)
        ]

        for i, chunk in enumerate(filtered_chunks, 1):
            start = max(0.0, chunk.start_seconds - sermon_start)
            end = max(0.0, chunk.end_seconds - sermon_start)
            lines.append(str(i))
            lines.append(f"{_format_srt_time(start)} --> {_format_srt_time(end)}")
            lines.append(chunk.text)
            lines.append("")
        content = "\n".join(lines)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        return output_path

    def generate_vtt(
        self,
        chunks: list[TranscriptChunkData],
        sermon_start: float,
        output_path: str,
        sermon_end: Optional[float] = None,
    ) -> str:
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        lines: list[str] = ["WEBVTT", ""]

        filtered_chunks = [
            c for c in chunks 
            if c.start_seconds >= sermon_start 
            and (sermon_end is None or c.end_seconds <= sermon_end)
        ]

        for chunk in filtered_chunks:
            start = max(0.0, chunk.start_seconds - sermon_start)
            end = max(0.0, chunk.end_seconds - sermon_start)
            lines.append(f"{_format_vtt_time(start)} --> {_format_vtt_time(end)}")
            lines.append(chunk.text)
            lines.append("")
        content = "\n".join(lines)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        return output_path

    def generate_ass(
        self,
        chunks: list[TranscriptChunkData],
        sermon_start: float,
        output_path: str,
        sermon_end: Optional[float] = None,
    ) -> str:
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        
        header = [
            "[Script Info]",
            "; Script generated by sermon-extraction",
            "ScriptType: v4.00+",
            "PlayResX: 384",
            "PlayResY: 288",
            "ScaledBorderAndShadow: yes",
            "",
            "[V4+ Styles]",
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
            "Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,50,1",
            "",
            "[Events]",
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
        ]

        lines = header.copy()

        filtered_chunks = [
            c for c in chunks 
            if c.start_seconds >= sermon_start 
            and (sermon_end is None or c.end_seconds <= sermon_end)
        ]

        for chunk in filtered_chunks:
            start = max(0.0, chunk.start_seconds - sermon_start)
            end = max(0.0, chunk.end_seconds - sermon_start)
            start_str = _format_ass_time(start)
            end_str = _format_ass_time(end)
            # Escape commas in text for ASS Dialogue line if necessary, though ASS usually handles it after the last comma
            text = chunk.text.replace("\n", "\\N")
            lines.append(f"Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{text}")

        content = "\n".join(lines)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        return output_path
